### ISSUE TITLE
Přečti si mě a do 10ti minut máš opraveno 

### ISSUE THREAD

**Issue by mohlerit** [PetraRockova/Ukol1#1]
Ahoj Petro,
zaskakuji za Verču, tak jsem se díval na tvůj kód. Skvělá práce, líbí se mi jak jsis se stránku vyhrála. Musím říct, že když jsem viděl tvé fotky z výletů a cest, tak se mi po cestování zastesklo. Hned bych zase někam jel :-)

Mám pro tebe pár tipů a také připomínek k tvému kódu:

V index.html na řádku dva máš tag `html` s atributem `lang`. Tan má hodnotu `en`, ale protože stránka je v češtině měl by nabývat hodnoty `cs`.

Dále jsem si všiml, že u své fotografie máš v názvu obrázku mezeru. Doporučuji ji nahradit podtržítkem a nebo pomlčkou. V HTML i CSS je zvykem zapisovat názvy tříd, souborů, složek atd. malými písmeny bez diakritiky a mezery nahrazovat pomlčkami nebo podtržítky. Funguje to, ale může se stát, že někde to fungovat nebude. Například mobilní prohlížečů je spousta verzí a proto je dobré se držet nějakých zajetách praxí :-).

Poslední věc v HTML je na řádku 130. Zatoulal se ti sem koncový tag `</p>` ale nikde nevidím jeho začátek. Tak jej jen odmař, protože dělá Jinak se jedná o nevalidní HTML kód.

Pro kontorlu hTML můžeš použít: https://validator.w3.org/

Jako poslední věc co jsem si všiml je že v CSS používáš hexadecimální zípis (#ffffff) tak i rgb zápis ( rgb(255, 255, 255) ) barev. To není špatně ale je dobré si vybrat jeden styl zápisu a ten držet pokud možno v celém CSS. Kód pak vypadá čistěji.

Jinak teda za mě povedená práce.

## Podmínky pro ohodnocení 

- [x] změnit hodnotu `lang` atributu v `html` tagu
- [x] změnit název obrázku `moje foto.jpg` na vlaidní název
- [x] Smazat zatoulaná koncový tag `</p>`

**Comment by PetraRockova** [comment]
Ahoj Martine, moc děkuju za milou zpětnou vazbu, dala jsem si záležet. O cestování mi ani nemluv, teď se člověk musí radovat aspoň z cesty do obchodu :) Tak snad brzy zase normálně po světě. 

Chyby jsem opravila, to </p> mělo začátek na řádku 93 (Státní zkouška bla bla...) ale nevím, proč se to tvářilo, jako že to nemá začátek... každopádně to tam stejně bylo asi navíc, dělala jsem tam s tím trochu čachry a předělávala to abych tam měla i tabulku, tak mi to tam asi zůstalo. Dala jsem to celé pryč a validátor hlásí že všechno OK. (Jinak díky za tip, budu používat).

Na barvy si dám pozor, resp. používám normálně RGB, ale řeknu ti přesně, jak toto vzniklo. Otevřela jsem totiž kouzelnou stránku https://www.w3schools.com/tags/ref_colornames.asp a mé srdéčko zaplesalo, takže jsem asi 2 hodiny zkoušela a hledala tu nej barvu, ale bohužel už jsem neřešila to, jak jí převést na RGB :) Takže asi tak. 

Teď by mělo být vše v pořádku.

Moc děkuju!

**Comment by mohlerit** [comment]
Na převod barev je toho mraky. Mám pocit, že to umí i Visual Code Studio nějak, ale nevím jak. Rychlé hledání mi našlo tnto online nástroj:
https://www.rapidtables.com/convert/color/hex-to-rgb.html

Jinak teda super a uzavírám issue a posílám hodnocení do classroom
